# Generated by Django 5.1.2 on 2024-10-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='room',
            new_name='list',
        ),
    ]
