# Generated by Django 5.1.2 on 2024-10-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_alter_item_priority_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='value',
            field=models.IntegerField(default=1),
        ),
    ]
