# Generated by Django 5.1.2 on 2024-10-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_priority_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
