# Generated by Django 5.1.2 on 2024-10-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_alter_item_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='priority',
            field=models.CharField(choices=[(1, 'High'), (2, 'Meddium'), (3, 'Low')], default=1, max_length=10),
        ),
    ]
