# Generated by Django 5.1.2 on 2024-10-24 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_alter_item_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='comments',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(db_default=datetime.date(2024, 10, 24)),
        ),
        migrations.AlterField(
            model_name='item',
            name='priority',
            field=models.CharField(choices=[('1', 'High'), ('2', 'Meddium'), ('3', 'Low')], default=3, max_length=10),
        ),
    ]
