# Generated by Django 5.1.2 on 2024-11-05 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_alter_item_comments_alter_item_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('WRK', 'Work'), ('FML', 'Family'), ('LRN', 'Learning'), ('TRV', 'Travelling'), ('OTH', 'Others')], default='OTH', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
