# Generated by Django 5.1.2 on 2024-11-06 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0012_list_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='user',
        ),
    ]
